name: Build lv_micropython unix port

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Install Dependencies
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev parallel libfreetype-dev librlottie-dev
    - name: Clone lv_micropython
      run: |
        git clone https://github.com/lvgl/lv_micropython.git .
        git checkout release/v8
    - name: Initialize lv_bindings submodule
      run: git submodule update --init --recursive lib/lv_bindings
    - name: Update Unix port submodules
      run: make -C ports/unix VARIANT=dev DEBUG=1 submodules
    - name: Checkout lv_bindings
      working-directory: ./lib/lv_bindings
      run: |
        git fetch --force ${{ github.event.repository.html_url }} "+refs/heads/*:refs/remotes/origin/*"
        git fetch --force ${{ github.event.repository.html_url }} "+refs/pull/*:refs/remotes/origin/pr/*"
        git checkout ${{ github.sha }} || git checkout ${{ github.event.pull_request.head.sha }}
        git submodule update --init --recursive
    - name: Build mpy-cross
      run: make -j $(nproc) -C mpy-cross
    - name: Build the unix port
      run: make -j $(nproc) -C ports/unix VARIANT=dev DEBUG=1
    - name: Run tests      
      run: |
        export XDG_RUNTIME_DIR=/tmp
        lib/lv_bindings/tests/run.sh
